server:
  port: 8661

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8661/eureka/
    server:
      waitTimeInMsWhenSyncEmpty: 0
